services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: argondb
      POSTGRES_USER: argon
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: argondb
      MYSQL_USER: argon
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

